apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: dns
data:
  Corefile: |
    .:53 {
        hosts /etc/hostsm/hosts {
          fallthrough
        }
        errors
        health {
          lameduck 5s
        }
        ready
        prometheus :9153
        forward . 8.8.8.8
        cache 30
        loop
        reload
        log
    }
