apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-k3s
spec:
  storageClassName: nfs-k3s
  capacity:
    storage: 500Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.22.22.102
    path: "/mnt/main_pool/k3s"
